# Generated by Django 5.2.7 on 2025-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('reservation_type', models.CharField(default='reservation', max_length=50)),
            ],
        ),
    ]
